name: Docker Build and Push

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the image'
        required: false
        type: string

jobs:
  build:
    name: Build and Push Docker Image
    uses: calebsargeant/reusable-workflows/.github/workflows/docker-bake-ghcr.yaml@18a0b2b9f5b45e3e3a49d0ec6dc6f3361644a507 # v1.0.5
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      bake_file: docker-bake.hcl
      bake_target: nmap-exporter
      push_target: nmap-exporter-push
      image_name: nmap-exporter
      platforms: linux/amd64,linux/arm64
      push: ${{ github.event_name != 'pull_request' }}
      enable_sbom: false
    secrets:
      registry_password: ${{ secrets.GITHUB_TOKEN }}
